[package]
name = "perg"
version = "0.5.0"
authors = ["Federico Guerinoni <guerinoni.federico@gmail.com>"]
edition = "2018"

[dependencies]
jwalk = "0.6.0"
clap = "3.1.5"

[dev-dependencies]
pretty_assertions = "1.0.0"

[profile.release]
lto = true
strip = true