[package]
name = "perg"
version = "0.3.0"
authors = ["Federico Guerinoni <guerinoni.federico@gmail.com>"]
edition = "2018"

[dependencies]
jwalk = "0.5"
clap = "3.0.0-beta.2"

[dev-dependencies]
pretty_assertions = "0.7.2"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3