[package]
name = "perg"
version = "0.5.0"
authors = ["Federico Guerinoni <guerinoni.federico@gmail.com>"]
edition = "2024"

[dependencies]
clap = "3.2.17"
jwalk = "0.8"

[dev-dependencies]
pretty_assertions = "1"

[profile.release]
lto = true
strip = true
