name: CI

on: [push, pull_request]

jobs:
  CI:
    name: CI
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Test
        run: cargo test

      - name: Install clippy
        run: rustup component add clippy

      - name: Run clippy
        run: cargo clippy -- -D warnings